#!/bin/sh
# run with sudo curl -s https://raw2.github.com/pimatic/pimatic/master/install/install-production | bash /dev/stdin
mkdir pimatic-app
cd pimatic-app
npm install pimatic --production
cp ./node_modules/pimatic/config_default.json ./config.json
