#!/bin/sh
# run with: curl -s https://raw.githubusercontent.com/pimatic/pimatic/development/install/install-git | sudo bash /dev/stdin development
BRANCH=$1
if [ ! -d pimatic-git ]
then
  mkdir pimatic-git
fi
cd pimatic-git
DIR="$(pwd)"
echo "Will installing pimatic and pimatic plugins from git branch $BRANCH into $DIR"
if [ ! -d pimatic-git ]
then
  mkdir node_modules
fi
for name in pimatic pimatic-cron pimatic-filebrowser pimatic-gpio pimatic-log-reader pimatic-mobile-frontend pimatic-pilight pimatic-ping pimatic-redirect pimatic-sispmctl pimatic-datalogger pimatic-shell-execute pimatic-pushover pimatic-sunrise pimatic-voice-recognition pimatic-mail
do
  cd "$DIR/node_modules"
  if [ -d $name ]
  then
    INSTALL="cd $name && git pull && npm install"
    echo "Updating $name from git: $INSTALL"
  else
    INSTALL="git clone https://github.com/pimatic/$name.git --depth 1 -b $BRANCH && cd $name && npm install"
    echo "Installing $name from git: $INSTALL"
  fi
  bash -c "$INSTALL"
done