#!/bin/sh
# run with sudo curl -s https://raw.githubusercontent.com/pimatic/pimatic/master/install/install-production | bash /dev/stdin pimatic-app
INSTALL_DIR=$1

if [ -z "$INSTALL_DIR" ]; then
  echo "No Install dir given"
  exit
fi

CURRENT_DIR=`pwd`
PLATFORM=`/usr/bin/env node -e 'console.log(process.versions.modules + "-" + process.arch + "-" + process.platform)'`
if [ "$PLATFORM" = "11-arm-linux" ]; then
  # Use precompiled source for arm:
  wget http://api.pimatic.org/download/pimatic/node-11-armhf-linux-latest.tar.gz -O /tmp/pimatic-node-11-armhf-linux-latest.tar.gz
  mkdir -p $INSTALL_DIR/node_modules/pimatic
  cd $INSTALL_DIR/node_modules/pimatic
  tar xzvf /tmp/pimatic-node-11-armhf-linux-latest.tar.gz --strip=1
  rm /tmp/pimatic-node-11-armhf-linux-latest.tar.gz
else
  npm install pimatic --prefix $INSTALL_DIR --production
fi
cd $CURRENT_DIR
cd $INSTALL_DIR
#cp ./node_modules/pimatic/config_default.json ./config.json
cd $CURRENT_DIR