#!/bin/sh
# run with: curl -s https://raw.github.com/pimatic/pimatic/development/install/install-git | sudo bash /dev/stdin development
BRANCH=$1
if [ ! -d pimatic-git ]
then
  mkdir pimatic-git
fi
cd pimatic-git
echo "Installing pimatic and pimatic plugins from git branch $BRANCH into $(pwd)"
for name in pimatic pimatic-cron pimatic-filebrowser pimatic-gpio pimatic-log-reader pimatic-mobile-frontend pimatic-pilight pimatic-ping pimatic-redirect pimatic-rest-api pimatic-sispmctl pimatic-datalogger pimatic-shell-execute pimatic-pushover
do
  INSTALL="npm install git+https://github.com/pimatic/$name.git#$BRANCH"
  if [ -f $name ]
  then
    echo "Updating $name from git: $INSTALL"
  else
    echo "Installing $name from git: $INSTALL"
  fi
  $INSTALL
done