#!/bin/sh
BRANCH=$TRAVIS_BRANCH
# cd ../..
# pwd -P
# for name in pimatic-cron pimatic-filebrowser pimatic-gpio pimatic-log-reader pimatic-mobile-frontend pimatic-pilight pimatic-ping pimatic-redirect pimatic-rest-api pimatic-sispmctl pimatic-datalogger pimatic-mail
# do
#   echo "Installing $name from git..." 
#   npm install git+https://github.com/pimatic/$name.git#$BRANCH
# done